frr version 10.2.2
frr defaults traditional
hostname br-rtr.au-team.irpo
log file /var/log/frr/frr.log
no ipv6 forwarding
!
interface tun1
 no ip ospf passive
exit
!
router ospf
 passive-interface default
 network 10.10.10.0/30 area 0
 network 192.168.30.0/28 area 0
exit
!
